ansible_connection: network_cli
local_asn: 11111
router_id: 1.1.1.1
neighbors:
  - remote_asn: 22222
    address: '2.2.2.2'
    update_source: 'Loopback0'
  - remote_asn: 33333
    address: '3.3.3.3'
    update_source: 'Loopback0'



acl:
  RULES:
    - seq: 10
      source: any
      dest_host: 8.8.8.8
      dest_port: 53
      action: permit
      protocol: tcp
    - seq: 20
      source: any
      dest_host: 8.8.8.8
      dest_port: 53
      action: permit
      protocol: udp     
    - seq: 30
      source: any
      dest_host: 222.222.222.222
      dest_port: 443
      action: permit
      protocol: tcp     