R1:
  local_asn: 11111
  neighbors:
    - remote_asn: 22222
      address: '2.2.2.2'
      update_source: 'Loopback0'
R2:
  local_asn: 22222
  neighbors:
    - remote_asn: 11111
      address: '1.1.1.1'
      update_source: 'Loopback0'
