---
- name: config ACL
  hosts: R1
  gather_facts: yes
  # role at playbook level
  # roles:
  # - acl_config
  tasks:
  # - name: remove acl
  #   ios_config:
  #     lines:
  #     -  no ip access-list extended INTERNET
  - name: print hostname
    debug:
      var: ansible_facts
  # - name: config acl
  #   ios_config:
  #     lines:
  #     -  "{{ item.seq }} {{ item.action }} {{ item.protocol }} any host {{ item.dest_host }} eq {{ item.dest_port }}"
  #     parents:
  #     - ip access-list extended INTERNET
  #   with_items:
  #     - "{{ acl.RULES }}"
  #   when: ansible_host == "192.168.50.61"

  - name: config acl
    ios_config:
      lines:
      -  "{{ item.seq }} {{ item.action }} {{ item.protocol }} any host {{ item.dest_host }} eq {{ item.dest_port }}"
      parents:
      - ip access-list extended INTERNET
    with_items:
      - "{{ acl.RULES }}"
    when: ansible_host == "192.168.50.61"