---
- name: BGP configuration on R1
  hosts: R1
  gather_facts: yes
  tasks:
    - name: print facts
      debug:
        var: ansible_network_os
    - name: 
      ios_bgp:
        config:
          bgp_as: "{{ local_asn }}"
          router_id: "{{ router_id }}"
          neighbors:
          - neighbor: "{{ item.address }}"
            remote_as: "{{ item.remote_asn }}"
            ebgp_multihop: 2
          networks:
          - prefix: 11.11.11.11
            masklen: 32
        operation: merge
      when: ansible_network_os == 'ios'
      with_items: 
      - "{{ neighbors }}"
- name: BGP configuration on R2
  hosts: R2
  gather_facts: yes
  tasks:
    - name: print facts
      debug:
        var: ansible_network_os
    - name: 
      ios_bgp:
        config:
          bgp_as: "{{ local_asn }}"
          router_id: "{{ router_id }}"
          neighbors:
          - neighbor: "{{ item.address }}"
            remote_as: "{{ item.remote_asn }}"
            ebgp_multihop: 2
          networks:
          - prefix: 22.22.22.22
            masklen: 32
        operation: merge
      when: ansible_network_os == 'ios'
      with_items: 
      - "{{ neighbors }}"
        
        